### PR TITLE
Update styles to match latest Sanity update

### PR DESCRIPTION
**Pull request by benjaminsehl**
In the latest Sanity update, there were number of styles that changed, like making objects only have borders on the left, which made Tabs look different than intended. This PR addresses that by simply updating a few border styles, such that the tabs are now restored to the original intended design. 

I've also added the small tweak to make tabs flat across the top, with rounding at the first and last child.

@azzlack Let me know if there is anything you would like to see — I'm happy to update the PR accordingly.

### CODE REVIEW

**Comment by benjaminsehl** [comment]
@azzlack — any chance you could review this? The default CSS in the new Sanity is really bugging me! I can of course alternatively fork and publish my own, but would love to have this as part of the main repo.

**Comment by niklas-may** [comment]
@azzlack would also love to see the broken styling fixed. @benjaminsehl is there a way to load you styles manually in the meantime?

**Comment by benjaminsehl** [comment]
@niklas-may — the only way to use my version is if I publish my fork to NPM. If I don't hear back from @azzlack in the next week or so, I'll go ahead and do that (at least until this gets reviewed). Would be ideal to keep everything in this repo though.

**Comment by azzlack** [comment]
Thanks for this update, sorry it took so long to merge it.

**Comment by benjaminsehl** [comment]
No worries! Glad you like it

**Pull request merged**
